#!/bin/bash

case "$1" in
	logout)
		echo "empty" > ~/.config/i3/current-theme
		i3-msg exit
		;;
	suspend)
		echo "empty" > ~/.config/i3/current-theme
		systemctl suspend
		;;
	reboot)
		echo "empty" > ~/.config/i3/current-theme
		systemctl reboot
		;;
	shutdown)
		echo "empty" > ~/.config/i3/current-theme
		systemctl poweroff
		;;
	*)
		echo "Usage: $0 {logout|suspend|reboot|shutdown}"
		exit 2
esac

exit 0
