#!/bin/bash

case "$1" in
	logout)
		echo "none" > /tmp/stat
		i3-msg exit
		;;
	suspend)
		echo "none" > /tmp/stat
		systemctl suspend
		;;
	reboot)
		echo "none" > /tmp/stat
		systemctl reboot
		;;
	shutdown)
		echo "none" > /tmp/stat
		systemctl poweroff
		;;
	*)
		echo "Usage: $0 {logout|suspend|reboot|shutdown}"
		exit 2
esac

exit 0
